<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<div class="container">
    <div class="row">
        <h1 style="margin-top: 20px">Bản giới thiệu một số API được phát triển thêm (không cần đăng nhập)</h1>
        <ul class="list-unstyled">
            <ul>
                <li><h2>Mục đích:</h2>
                    <ul>
                        <li>Nhằm lấy thông tin sản phẩm đơn giản hơn cho các nhà phát triển.</li>
                        <li>Phục vụ cho quảng cáo sản phẩm ở các trang Web khác</li>
                    </ul>
                </li>
            </ul>

            <ul>
                <li><h2>Chức năng:</h2>
                    <ul>
                        <li>Lấy thông tin tất cả các sản phẩm.</li>
                        <li>Lấy thông tin sản phẩm bằng ID của sản phẩm.</li>
                        <li>Lấy thông tin sản phẩm bằng ID của category.</li>
                    </ul>
                </li>
            </ul>
            <ul>
                <li><h2>Hướng dẫn sử dụng:</h2>
                    <ul>
                        <li>Lấy thông tin tất cả các sản phẩm:</li>
                            <ul>
                                <a href="http://pencilicious.site/rest/V1/rest-api/product">
                                    http://pencilicious.site/rest/V1/rest-api/product
                                </a>
                            </ul>
                        <li>Lấy thông tin sản phẩm bằng ID của sản phẩm: 
                            <ul>
                                http://pencilicious.site/rest/V1/rest-api/product/:id (với :id thay bằng id của sản phẩm)    
                            </ul>
                            <ul> VD: id = 10
                                <a href="http://pencilicious.site/rest/V1/rest-api/product/10">
                                    http://pencilicious.site/rest/V1/rest-api/product/10
                                </a>    
                            </ul>
                        </li>
                        <li>Lấy thông tin sản phẩm bằng ID của category: 
                            <ul>
                                http://pencilicious.site/rest/V1/rest-api/product/category/:id  (với :id thay bằng id của category)
                            </ul>
                            <ul> VD: id = 3     
                                <a href="http://pencilicious.site/rest/V1/rest-api/product/category/3">
                                    http://pencilicious.site/rest/V1/rest-api/product/category/3
                                </a>    
                            </ul>
                        </li>
                    </ul>
                </li>
            </ul>

            <ul>
                <li><h2>Hướng dẫn cài đặt:</h2>
                    <ul>
                        <li>Bước 1: Copy thư mục UET/API vào thư mục app/code trong source.</li>
                        <li>Bước 2: Cập nhật module của Magento.
                            <ul>php bin/magento setup:upgrade</ul>
                        </li>
                        <li>Bước 3: Flush Cache bằng lệnh:
                            <ul>php bin/magento cache:flush</ul>
                        </li>
                    </ul>
                </li>
            </ul>
        </ul>
    </div>
</div>